[package]
name = "nibble"
version = "0.1.5"
edition = "2024"
authors = ["Mysz Team"]
description = "Mysz •<:3O-~"

[dependencies]
mysz-core = "0.5.0"

clap = { version = "4.4", features = ["derive", "env"] }
anyhow = "1.0"
tempfile = "3.8"
dirs = "5.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
flate2 = "1.0"
tar = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1.2"
kdl = "6.7.1"
